<div id="pwd-document-images" class="section">
<table class="tablesaw" data-tablesaw-mode="stack">
<thead>
    <tr>
        <th>Image</th>
        <th>Source</th>
        <th>Location</th>
    </tr>
</thead>
<tbody>
<?php foreach ($documentImages as $docImage): ?>
<?php
$source = null;
if ($docImage['source_id']) {
    $source = $this->api()->read('items', $docImage['source_id'])->getContent();
}
$image = null;
if ($docImage['image_id']) {
    $image = $this->api()->read('items', $docImage['image_id'])->getContent();
}
?>
    <tr>
        <td><?php echo $image
            ? $this->hyperlink(
                '[view in document viewer]',
                $this->url(
                    'admin/pwd/viewer',
                    ['document-image-id' => $docImage['id']],
                    ['fragment' => $docImage['page_number'] ? sprintf('page%s', $docImage['page_number']) : null]
                )
            )
            : '[no image]'; ?></td>
        <td><?php echo $source ? $source->link($source->displayTitle()) : '[no source]'; ?></td>
        <td><?php echo $docImage['location']; ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
