<div id="pwd-document-images" class="section">
<table class="tablesaw" data-tablesaw-mode="stack">
<thead>
    <tr>
        <th>Image</th>
        <th>Source</th>
        <th>Source location</th>
    </tr>
</thead>
<tbody>
<?php foreach ($documentImages as $docImage): ?>
<?php
$source = null;
if ($docImage['source_id']) {
    $source = $this->api()->read('items', $docImage['source_id'])->getContent();
}
$image = null;
if ($docImage['image_id']) {
    $image = $this->api()->read('items', $docImage['image_id'])->getContent();
}
$sourceText = [];
if ($source) {
    $sourceText[] = ucfirst($docImage['source_type']);
    $sourceText[] = $source->link($source->displayTitle());
} else {
    $sourceText[] = '[no source]';
}
$imageText = [];
if ($image) {
    $imageText[] = $image->link($image->displayTitle());
    if ($image->media()) {
        $imageText[] = $this->hyperlink(
            '[open in viewer]',
            $this->url(
                'admin/pwd/viewer',
                ['document-image-id' => $docImage['id']],
                ['fragment' => $docImage['page_number'] ? sprintf('page%s', $docImage['page_number']) : null]
            )
        );
    } else {
        $imageText[] = '[no pages]';
    }
} else {
    $imageText[] = '[no image]';
}
?>
    <tr>
        <td><?php echo implode(' : ', $imageText); ?></td>
        <td><?php echo implode(' : ', $sourceText); ?></td>
        <td><?php echo $docImage['location']; ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
