<div id="pwd-document-instances" class="section">
<table class="tablesaw" data-tablesaw-mode="stack">
<thead>
    <tr>
        <th></th>
        <th>In source</th>
        <th>Source location</th>
        <th>In image</th>
    </tr>
</thead>
<tbody>
<?php foreach ($documentInstances as $instance): ?>
<?php
$source = null;
if ($instance['source_id']) {
    $source = $this->api()->read('items', $instance['source_id'])->getContent();
}
$image = null;
if ($instance['image_id']) {
    $image = $this->api()->read('items', $instance['image_id'])->getContent();
}
$sourceText = [];
if ($source) {
    $sourceText[] = ucfirst($instance['source_type']);
    $sourceText[] = $source->link($source->displayTitle());
} else {
    $sourceText[] = '[no source]';
}
?>
    <tr>
        <td><?php echo $this->hyperlink(
            '[open in viewer]',
            $this->url('admin/pwd/viewer',['document-instance-id' => $instance['id']])
        ) ?></td>
        <td><?php echo implode(': ', $sourceText); ?></td>
        <td><?php echo $instance['location']; ?></td>
        <td><?php echo $image ? sprintf('%s (%s pages)', $image->link($image->displayTitle()), count($image->media())) : '[no image]'; ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
