<div id="pwd-document-images" class="section">
<table class="tablesaw" data-tablesaw-mode="stack">
<thead>
    <tr>
        <th>Image</th>
        <th>Collection</th>
        <th>Location</th>
    </tr>
</thead>
<tbody>
<?php foreach ($documentImages['pwd_document_collection'] as $docImage): ?>
<?php
$collection = null;
if ($docImage['collection_id']) {
    $collection = $this->api()->read('items', $docImage['collection_id'])->getContent();
}
$image = null;
if ($docImage['image_id']) {
    $image = $this->api()->read('items', $docImage['image_id'])->getContent();
}
?>
    <tr>
        <td><?php echo $image ? $image->link($image->displayTitle()) : '[no image]'; ?></td>
        <td><?php echo $collection ? $collection->link($collection->displayTitle()) : '[no collection]'; ?></td>
        <td><?php echo $docImage['location']; ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
