<div id="pwd-image-documents" class="section">
<table class="tablesaw" data-tablesaw-mode="stack">
<thead>
    <tr>
        <th>Document</th>
        <th>Source</th>
        <th>Source location</th>
    </tr>
</thead>
<tbody>
<?php foreach ($imageDocuments as $imageDoc): ?>
<?php
$source = null;
if ($imageDoc['source_id']) {
    $source = $this->api()->read('items', $imageDoc['source_id'])->getContent();
}
$sourceText = [];
if ($source) {
    $sourceText[] = ucfirst($imageDoc['source_type']);
    $sourceText[] = $source->link($source->displayTitle());
} else {
    $sourceText[] = '[no source]';
}
$document = null;
if ($imageDoc['document_id']) {
    $document = $this->api()->read('items', $imageDoc['document_id'])->getContent();
}
?>
    <tr>
        <td><?php echo $document ? $document->link($document->displayTitle()) : '[no document]'; ?></td>
        <td><?php echo implode(' : ', $sourceText); ?></td>
        <td><?php echo $imageDoc['location']; ?></td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>
</div>
